### ISSUE TITLE
Forum and software listing site instead of/alongside the Facebook group

### ISSUE THREAD

**Issue by LinuxinaBit** [TheByteAttic/AgonORIGINS#2]
I recently found out about this project and it looks really cool. I was wondering if there was any collection of programs or accessible discussion, but it turns out it’s all on Facebook.
I have a complete distaste of it and have no desire to ever create an account.

For the communication something like a forum would be much better anyway as they are much easier to search and find help for what you need. Would it be possible to create a forum with something like phpbb (there are free hosting providers out there) for more accessible communication without big tech?

As for the software listing, I have actually been working on a static site that can be hosted with something like Github Pages that lists out uploaded games with properties set by json(like) files.

Keep in mind this is still very early in development, but take a look and see what you think:
https://codeberg.org/B2server/Program-Library/
Demo SIte: https://b2server.codeberg.page/Program-Library/@main/

**Comment by TheByteAttic** [comment]
There are multiple discord servers, but I don't take part; too many places.
